experiment_name: fracture-yolo
run_name: final_model_after_tuning
model: yolov8n.pt

# Point this to your YOLO dataset YAML file.
data_config: data/raw/hbfmid/data.yaml

epochs: 1 # eher auf 20 machen weil nicht so grosses dataset
imgsz: 640
batch: 8 # wird durch tuning.py geliefert
device: cpu # 0 falls gpu

# These values are examples and can be tuned in tune.py
learning_rate: 0.01
weight_decay: 0.0005
